#!/bin/bash
# This hook is sourced after a new virtualenv is activated.
pip install pip -U
pip install yapf jedi service_factory ipdb numpydoc sphinx wheel pyscaffold pytest pytest-cov pyflakes
pip install ipython jsonschema twine pyzmq tornado

