#!/bin/bash
# This hook is sourced after a new virtualenv is activated.
pip install autopep8 jedi service_factory ipdb numpydoc sphinx wheel pyscaffold pytest pytest-cov pyflakes
pip install ipython jsonschema
